import { _electron as electron, expect, type ElectronApplication } from '@playwright/test';
import { readFile, mkdir, writeFile, stat } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { probe } from '../electron/media';
import { binPath, run } from '../electron/process';

const root = resolve('.');
const fixture = JSON.parse(await readFile(join(root, 'artifacts/latest-media.json'), 'utf8')) as { projectPath: string; sourceFiles: string[] };
const id = new Date().toISOString().replace(/[:.]/g, '-');
const outputDir = join(root, 'output/playwright', id);
const dataDir = join(root, '.vlogtool-test', id);
await mkdir(outputDir, { recursive: true }); await mkdir(dataDir, { recursive: true });
const env = Object.fromEntries(Object.entries(process.env).filter((item): item is [string, string] => item[1] !== undefined && item[0] !== 'ELECTRON_RUN_AS_NODE'));
let application: ElectronApplication | undefined;
const launch = () => electron.launch({ executablePath: join(root, 'node_modules/electron/dist/electron.exe'), args: [root], cwd: root, env: { ...env, VLOGTOOL_TEST_DATA: dataDir }, timeout: 30000 });
const errors: string[] = [];
try {
  application = await launch();
  const page = await application.firstWindow();
  page.on('pageerror', error => errors.push(error.message));
  await expect(page.getByRole('button', { name: '＋ 영상 가져오기' })).toBeEnabled();
  await page.getByRole('combobox', { name: '프로젝트 화면 비율' }).selectOption('16:9');
  await writeFile(join(outputDir, 'initial-ui.txt'), await page.locator('body').ariaSnapshot());
  await page.screenshot({ path: join(outputDir, '01-empty.png') });
  const security = await application.evaluate(({ BrowserWindow }) => {
    const preferences = (BrowserWindow.getAllWindows()[0].webContents as unknown as { getLastWebPreferences(): { contextIsolation: boolean; nodeIntegration: boolean; sandbox: boolean } }).getLastWebPreferences();
    return { contextIsolation: preferences.contextIsolation, nodeIntegration: preferences.nodeIntegration, sandbox: preferences.sandbox };
  });
  expect(security).toEqual({ contextIsolation: true, nodeIntegration: false, sandbox: true });
  expect(await page.evaluate(() => typeof (window as any).require)).toBe('undefined');
  await application.evaluate(({ dialog }, filePaths) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths }); }, fixture.sourceFiles.slice(0, 2));
  await page.getByRole('button', { name: '＋ 영상 가져오기' }).click();
  await expect(page.getByTestId('timeline-clip')).toHaveCount(2, { timeout: 60000 });
  await expect(page.locator('.task-overlay')).toHaveCount(0);
  await expect(page.locator('video')).toHaveJSProperty('readyState', 4, { timeout: 15000 });
  const firstName = await page.getByTestId('timeline-clip').first().locator('strong').innerText();
  await page.getByRole('button', { name: '클립 1 순서 이동' }).dragTo(page.getByTestId('timeline-clip').nth(1));
  await expect(page.getByTestId('timeline-clip').nth(1).locator('strong')).toHaveText(firstName);
  await page.getByRole('button', { name: '실행 취소' }).click();
  await expect(page.getByTestId('timeline-clip').first().locator('strong')).toHaveText(firstName);
  const zoomControl = page.getByRole('slider', { name: '타임라인 확대' });
  await zoomControl.focus(); await zoomControl.press('End');
  await expect(zoomControl).toHaveValue('160');
  const view = page.locator('.track-scroll');
  await view.hover(); await page.mouse.wheel(0, 60);
  await expect.poll(() => view.evaluate(el => el.scrollLeft)).toBeGreaterThan(0);
  const bounds = await view.boundingBox();
  if (!bounds) throw new Error('Missing timeline viewport');
  await page.mouse.move(bounds.x + bounds.width - 9, bounds.y + 15); await page.mouse.down();
  await expect.poll(() => view.evaluate(el => el.scrollLeft)).toBeGreaterThan(65);
  await page.mouse.up();
  const beforePan = await view.evaluate(el => el.scrollLeft);
  await page.mouse.move(bounds.x + 200, bounds.y + 15); await page.mouse.down({ button: 'middle' });
  await page.mouse.move(bounds.x + 250, bounds.y + 15, { steps: 8 });
  await expect.poll(() => view.evaluate(el => el.scrollLeft)).toBeLessThan(beforePan - 20);
  await page.mouse.up({ button: 'middle' });
  await page.keyboard.down('Control'); await page.mouse.wheel(0, 180); await page.keyboard.up('Control');
  await expect.poll(async () => Number(await zoomControl.inputValue())).toBeLessThan(160);
  await zoomControl.focus(); await zoomControl.press('Home');
  for (let i = 0; i < 40; i++) await zoomControl.press('ArrowRight');
  await expect(zoomControl).toHaveValue('60');
  const ruler = await page.locator('.ruler').boundingBox();
  if (!ruler) throw new Error('Missing timeline ruler');
  await page.mouse.move(ruler.x + 60, ruler.y + 16); await page.mouse.down();
  await page.mouse.move(ruler.x + 300, ruler.y + 16, { steps: 12 });
  await expect(page.locator('.timecode')).toContainText('00:05:00');
  await page.mouse.move(ruler.x + 120, ruler.y + 16, { steps: 8 });
  await expect(page.locator('.timecode')).toContainText('00:02:00');
  await page.mouse.up();
  await page.getByRole('slider', { name: '재생 위치' }).dragTo(page.locator('.ruler'), { targetPosition: { x: 240, y: 16 } });
  await expect(page.locator('.timecode')).toContainText('00:04:00');
  const body = await page.getByTestId('timeline-clip').first().boundingBox();
  if (!body) throw new Error('Missing clip');
  await page.mouse.move(body.x + 50, body.y + 35); await page.mouse.down();
  await page.mouse.move(body.x + 150, body.y + 35, { steps: 10 }); await page.mouse.up();
  // A body drag within its original insertion slot keeps the initial preview and clip order.
  await expect(page.locator('.timecode')).toContainText('00:00:25');
  await expect(page.getByTestId('timeline-clip').first().locator('strong')).toHaveText(firstName);
  await page.getByTestId('timeline-clip').first().click({ position: { x: 61, y: 18 } });
  await page.getByRole('spinbutton', { name: '시작 프레임' }).fill('30');
  await page.getByRole('spinbutton', { name: '종료 프레임' }).click();
  await page.getByRole('spinbutton', { name: '종료 프레임' }).fill('75');
  await page.getByRole('heading', { name: '클립 속성' }).click();
  await expect(page.getByRole('spinbutton', { name: '종료 프레임' })).toHaveValue('75');
  await page.getByTestId('timeline-clip').nth(1).click({ position: { x: 1, y: 18 } });
  await page.getByRole('spinbutton', { name: '시작 프레임' }).fill('15');
  await page.getByRole('spinbutton', { name: '종료 프레임' }).click();
  await page.getByRole('spinbutton', { name: '종료 프레임' }).fill('90');
  await page.getByRole('heading', { name: '클립 속성' }).click();
  await page.getByTestId('timeline-clip').first().click({ position: { x: 30, y: 18 } });
  await page.keyboard.press('s');
  await expect(page.getByTestId('timeline-clip')).toHaveCount(3);
  await page.keyboard.press('Control+z'); await expect(page.getByTestId('timeline-clip')).toHaveCount(2);
  await page.keyboard.press('Control+y'); await expect(page.getByTestId('timeline-clip')).toHaveCount(3);
  await page.keyboard.press('Control+z');
  await page.getByRole('textbox', { name: '프로젝트 이름' }).fill('한글 경로 UI 검증 S');
  await expect(page.getByTestId('timeline-clip')).toHaveCount(2);
  await page.getByRole('heading', { name: '타임라인' }).click();
  await page.getByTestId('timeline-clip').nth(1).click({ position: { x: 1, y: 18 } });
  await page.locator('.ruler').click({ position: { x: 90, y: 28 } });
  await page.getByRole('button', { name: '이전 프레임' }).click();
  await expect(page.locator('.timecode')).toContainText('00:01:14');
  await page.getByRole('button', { name: '다음 프레임' }).click();
  await expect(page.locator('.timecode')).toContainText('00:01:15');
  await expect(page.locator('.exact-frame')).toBeVisible();
  await page.screenshot({ path: join(outputDir, '02-editor.png') });
  await page.getByRole('button', { name: '재생', exact: true }).click();
  await expect.poll(() => page.locator('video').evaluate((v: HTMLVideoElement) => v.currentTime)).toBeGreaterThan(0.9);
  await page.getByRole('button', { name: '일시 정지' }).click();
  await expect(page.getByRole('alert')).toHaveCount(0);
  await page.getByTestId('timeline-clip').first().click({ position: { x: 30, y: 30 } });
  await page.getByRole('spinbutton', { name: '밝기 값' }).fill('25');
  await page.getByRole('spinbutton', { name: '밝기 값' }).press('Enter');
  await page.getByRole('spinbutton', { name: '채도 값' }).fill('-100');
  await page.getByRole('spinbutton', { name: '채도 값' }).press('Enter');
  await expect(page.locator('.exact-frame')).toBeVisible();
  await page.screenshot({ path: join(outputDir, '04-color.png') });
  await page.getByTestId('timeline-clip').nth(1).click({ position: { x: 30, y: 30 } });
  await expect(page.getByRole('spinbutton', { name: '밝기 값' })).toHaveValue('0');
  await page.getByTestId('timeline-clip').first().click({ position: { x: 30, y: 30 } });
  await expect(page.getByRole('spinbutton', { name: '밝기 값' })).toHaveValue('25');
  // One continuous slider gesture must undo as a single edit.
  const slider = page.getByRole('slider', { name: '대비', exact: true });
  const sliderBox = await slider.boundingBox();
  if (!sliderBox) throw new Error('Missing color slider');
  await page.mouse.move(sliderBox.x + sliderBox.width / 2, sliderBox.y + sliderBox.height / 2); await page.mouse.down();
  await page.mouse.move(sliderBox.x + sliderBox.width * 0.8, sliderBox.y + sliderBox.height / 2, { steps: 10 });
  await expect(page.locator('.exact-frame')).toHaveCount(0);
  const previewBounds = await page.locator('.preview-stage').boundingBox();
  if (!previewBounds) throw new Error('Missing preview');
  const sampleArea = { x: Math.round(previewBounds.x + previewBounds.width * 0.6), y: Math.round(previewBounds.y + previewBounds.height * 0.7), width: 4, height: 4 };
  const liveImage = join(outputDir, 'live-color-pixel.png'), stillImage = join(outputDir, 'still-color-pixel.png');
  const liveState = await page.evaluate(() => {
    const v = document.querySelector('video')!; const canvas = document.createElement('canvas'); canvas.width = v.videoWidth; canvas.height = v.videoHeight;
    const context = canvas.getContext('2d')!; context.drawImage(v, 0, 0);
    return { matrix: document.querySelector('feColorMatrix')?.getAttribute('values'), pixel: Array.from(context.getImageData(1200, 800, 1, 1).data), contrast: (document.querySelector('[aria-label="대비 값"]') as HTMLInputElement).value };
  });
  await page.screenshot({ path: liveImage, clip: sampleArea });
  await page.mouse.up();
  await expect(page.locator('.exact-frame')).toBeVisible({ timeout: 15000 });
  await page.screenshot({ path: stillImage, clip: sampleArea });
  const readPixel = async (path: string) => Array.from((await run(binPath(root, 'ffmpeg'), ['-v', 'error', '-i', path, '-vf', 'format=rgb24,crop=1:1:1:1', '-frames:v', '1', '-f', 'rawvideo', 'pipe:1'])).stdout);
  const livePixel = await readPixel(liveImage), stillPixel = await readPixel(stillImage);
  expect(livePixel.every((value, i) => Math.abs(value - stillPixel[i]) <= 4)).toBe(true);
  await expect(page.getByRole('spinbutton', { name: '대비 값' })).not.toHaveValue('0');
  await page.getByRole('button', { name: '실행 취소' }).click();
  await expect(page.getByRole('spinbutton', { name: '대비 값' })).toHaveValue('0');
  await expect(page.getByRole('spinbutton', { name: '밝기 값' })).toHaveValue('25');
  const saved = join(outputDir, '한글 프로젝트.vlog.json');
  await application.evaluate(({ dialog }, filePath) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath }); }, saved);
  await page.getByRole('button', { name: '저장 Ctrl S' }).click();
  await expect.poll(async () => { try { return (await stat(saved)).size; } catch { return 0; } }).toBeGreaterThan(100);
  expect(JSON.parse(await readFile(saved, 'utf8')).clips[0].color).toEqual({ brightness: 25, contrast: 0, saturation: -100, warmth: 0 });
  const exported = join(outputDir, '화면에서 내보낸 영상.mp4');
  await application.evaluate(({ dialog }, filePath) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath }); }, exported);
  await page.getByRole('button', { name: '내보내기 ↗' }).click();
  await expect(page.locator('footer')).toContainText('MP4 내보내기 완료', { timeout: 60000 });
  expect(Number((await probe(root, exported)).streams.find(s => s.codec_type === 'video')?.nb_frames)).toBe(120);
  await page.getByTestId('timeline-clip').first().click({ position: { x: 2, y: 18 } });
  await page.keyboard.press('Delete'); await expect(page.getByTestId('timeline-clip')).toHaveCount(1);
  await page.keyboard.press('Control+z'); await expect(page.getByTestId('timeline-clip')).toHaveCount(2);
  await application.evaluate(({ dialog }, path) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [path] }); }, saved);
  await page.getByRole('button', { name: '열기', exact: true }).click();
  await expect(page.locator('footer')).toContainText('프로젝트 열기 완료', { timeout: 60000 });
  await expect(page.getByTestId('timeline-clip')).toHaveCount(2);
  await expect(page.getByRole('textbox', { name: '프로젝트 이름' })).toHaveValue('한글 경로 UI 검증 S');
  await page.getByTestId('timeline-clip').first().click({ position: { x: 20, y: 30 } });
  await expect(page.getByRole('spinbutton', { name: '채도 값' })).toHaveValue('-100');
  const missingProject = JSON.parse(await readFile(saved, 'utf8'));
  missingProject.media[0].path = join(outputDir, '이동된 원본.mp4');
  const missingPath = join(outputDir, '원본 누락 검증.vlog.json');
  await writeFile(missingPath, JSON.stringify(missingProject));
  await application.evaluate(({ dialog }, path) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [path] }); }, missingPath);
  await page.getByRole('button', { name: '열기', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('원본을 확인하지 못한 항목', { timeout: 60000 });
  await expect(page.getByRole('button', { name: '내보내기 ↗' })).toBeDisabled();
  await page.getByRole('button', { name: '안내 닫기' }).click();
  await application.evaluate(({ dialog }, path) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [path] }); }, saved);
  await page.getByRole('button', { name: '열기', exact: true }).click();
  await expect(page.getByRole('button', { name: '내보내기 ↗' })).toBeEnabled({ timeout: 60000 });
  await application.close(); application = await launch();
  const restored = await application.firstWindow();
  restored.on('pageerror', error => errors.push(error.message));
  await expect(restored.getByRole('button', { name: '작업 복구' })).toBeVisible();
  await restored.getByRole('button', { name: '작업 복구' }).click();
  await expect(restored.getByTestId('timeline-clip')).toHaveCount(2, { timeout: 60000 });
  await expect(restored.getByRole('textbox', { name: '프로젝트 이름' })).toHaveValue('한글 경로 UI 검증 S');
  await restored.screenshot({ path: join(outputDir, '03-restored.png') });
  expect(errors).toEqual([]);
  const report = { date: new Date().toISOString(), security, errors, saved, exported, outputDir,
    liveState, livePixel, stillPixel,
    checks: ['actual Electron window launch', 'renderer isolation', 'file selection import (native dialog stub)', 'video loaded', 'reorder grip', 'ruler drag both directions', 'playhead drag', 'clip body same-slot drag preserves order', 'wheel horizontal scroll', 'edge auto-scroll', 'middle mouse pan', 'Ctrl+wheel zoom', 'per clip brightness/saturation', 'one gesture one undo', 'live SVG vs FFmpeg still color pixels', 'numeric trim', 'split', 'undo/redo', 'typing shortcut isolation', 'frame stepping across cut', 'playback', 'save with correction', 'export from UI', 'ripple delete', 'open project restores correction', 'missing media notification and export disabled', 'restart/recovery'],
    limitations: ['native OS dialog is stubbed in automation', 'physical drag/drop not tested', 'live playback seamlessness not measured', 'microphone capture verified separately by verify-narration.ts'] };
  await writeFile(join(outputDir, 'report.json'), JSON.stringify(report, null, 2));
  await writeFile(join(root, 'artifacts/latest-desktop.json'), JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report, null, 2));
} catch (e) {
  if (application) { const p = await application.firstWindow(); await p.screenshot({ path: join(outputDir, 'failure.png') }); console.error(await p.locator('body').innerText()); }
  throw e;
} finally { await application?.close(); }
