import { _electron as electron, expect } from '@playwright/test';
import { mkdir, readFile, writeFile, readdir } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
import { ProjectSchema } from '../src/shared/project';
import { addCaption } from '../src/shared/captions';
import { probe } from '../electron/media';

const root = resolve('.'), id = `export-${Date.now()}`, out = join(root, 'output/playwright', id), data = join(root, '.vlogtool-test', id);
await mkdir(out, { recursive: true }); await mkdir(join(data, 'work'), { recursive: true });
const fixture = JSON.parse(await readFile(join(root, 'artifacts/latest-media.json'), 'utf8'));
let project = ProjectSchema.parse(JSON.parse(await readFile(fixture.projectPath, 'utf8')));
project.clips = Array.from({ length: 8 }, (_, i) => ({ ...structuredClone(project.clips[i % 2]), id: randomUUID(), inFrame: 37, outFrame: 120 }));
project.captions = []; project.narrations = []; project.decorations = [];
project = addCaption(project, project.clips[0].id, 'title', 0).project;
project.captions[0].text = '덮어쓰기 · 진행률 확인';
await writeFile(join(data, 'work/recovery.vlog.json'), JSON.stringify(project));
const env = Object.fromEntries(Object.entries(process.env).filter(([k, v]) => v !== undefined && k !== 'ELECTRON_RUN_AS_NODE'));
const app = await electron.launch({ executablePath: join(root, 'node_modules/electron/dist/electron.exe'), args: [root], env: { ...env, VLOGTOOL_TEST_DATA: data } });
const destination = join(out, '이미 있는 영상.mp4'), previous = Buffer.from('previous export must survive cancellation');
try {
  const page = await app.firstWindow(); await page.evaluate('globalThis.__name = fn => fn');
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.getByRole('button', { name: '작업 복구' }).click();
  await expect(page.getByTestId('timeline-clip')).toHaveCount(8, { timeout: 60000 });
  await expect(page.locator('.task-overlay')).toHaveCount(0);
  await page.evaluate(() => { (window as any).exportEvents = []; window.editor.onProgress(p => { if (p.kind === 'export') (window as any).exportEvents.push(p); }); });
  await writeFile(destination, previous);
  await app.evaluate(({ dialog }) => { dialog.showSaveDialog = async () => ({ canceled: true, filePath: '' }); });
  await page.getByRole('button', { name: '내보내기 ↗' }).click(); await expect(page.locator('.task-overlay')).toHaveCount(0);
  expect(await readFile(destination)).toEqual(previous);
  // A successful native Save dialog return includes the user's replace consent.
  await app.evaluate(({ dialog }, path) => { dialog.showSaveDialog = async (first: any, second?: any) => { (globalThis as any).saveOptions = second ?? first; return { canceled: false, filePath: path }; }; }, destination);
  await page.getByRole('button', { name: '내보내기 ↗' }).click();
  await expect(page.locator('.task-frames')).toBeVisible({ timeout: 30000 });
  await expect(page.getByRole('progressbar', { name: '현재 단계 진행률' })).toBeVisible();
  await expect.poll(() => page.locator('.task-frames').textContent()).not.toContain('영상 0.0초');
  await page.screenshot({ path: join(out, 'export-progress.png') });
  await page.getByRole('button', { name: '작업 취소', exact: true }).click();
  await expect(page.locator('.task-overlay')).toHaveCount(0, { timeout: 15000 });
  expect(await readFile(destination)).toEqual(previous);
  await page.evaluate(() => { (window as any).exportEvents = []; });
  await page.getByRole('button', { name: '내보내기 ↗' }).click();
  await expect(page.locator('footer')).toContainText('MP4 내보내기 완료', { timeout: 90000 });
  const events = await page.evaluate(() => (window as any).exportEvents.filter((p: any) => p.exportStatus));
  const stages = [...new Set(events.map((p: any) => p.exportStatus.stage))];
  expect(stages).toEqual(['prepare', 'captions', 'encode', 'verify', 'save', 'done']);
  const frames = events.filter((p: any) => p.exportStatus.stage === 'encode').map((p: any) => p.exportStatus.renderedFrames);
  expect(frames.at(-1)).toBe(664); expect(frames.every((n: number, i: number) => !i || n >= frames[i - 1])).toBe(true);
  expect(events.at(-1).percent).toBe(100);
  expect(events.slice(0, -1).every((p: any) => p.percent < 100)).toBe(true);
  const meta = await probe(root, destination);
  expect(Number(meta.streams.find(s => s.codec_type === 'video')?.nb_frames)).toBe(664);
  expect(Number(meta.streams.find(s => s.codec_type === 'audio')?.duration)).toBeCloseTo(664 / 30, 1);
  const saveOptions = await app.evaluate(() => (globalThis as any).saveOptions);
  expect(saveOptions.properties).toContain('showOverwriteConfirmation');
  expect((await readdir(out)).filter(name => name.endsWith('.partial.mp4'))).toEqual([]);
  expect(errors).toEqual([]);
  await writeFile(join(out, 'report.json'), JSON.stringify({ destination, stages, frames, events, saveOptions, checks: ['cancel save dialog', 'cancel render preserves existing file', 'native-confirmed overwrite', 'stage progress UI', '664 exact frames', 'audio duration', 'no partial files'], errors }, null, 2));
  console.log(`Export verified: ${out}`);
} finally { await app.close(); }
